%%% start preambling . . .  %%%
\documentclass{article}

% required 
\usepackage[hyphens]{url} % this wraps my URL versus letting it spill across the page, a bad habit LaTeX has

\usepackage{Sweave}
\usepackage{graphicx}
\usepackage{natbib}
\usepackage{amsmath}
\usepackage{textcomp}%amoung other things, it allows degrees C to be added
\usepackage{float}
\usepackage[utf8]{inputenc} % allow funny letters in citaions 
\usepackage[nottoc]{tocbibind} %should add Refences to the table of contents?
\usepackage{amsmath} % making nice equations 
\usepackage{listings} % add in stan code
\usepackage{xcolor}
\usepackage{capt-of}%alows me to set a caption for code in appendix 
\usepackage[export]{adjustbox} % adding a box around a map
\usepackage{lineno}
\linenumbers
% recommended! Uncomment the below line and change the path for your computer!
% \SweaveOpts{prefix.string=/Users/Lizzie/Documents/git/teaching/demoSweave/Fig.s/demoFig, eps=FALSE} 
%put your Fig.s in one place! Also, note that here 'Fig.s' is the folder and 'demoFig' is what each 
% Fig. produced will be titled plus its number or label (e.g., demoFig-nqpbetter.pdf')
% make your captioning look better
\usepackage[small]{caption}

\usepackage{xr-hyper} %refer to Fig.s in another document
\usepackage{hyperref}

\setlength{\captionmargin}{30pt}
\setlength{\abovecaptionskip}{0pt}
\setlength{\belowcaptionskip}{10pt}

% optional: muck with spacing
\topmargin -1.5cm        
\oddsidemargin 0.5cm   
\evensidemargin 0.5cm  % same as oddsidemargin but for left-hand pages
\textwidth 15.59cm
\textheight 21.94cm 
% \renewcommand{\baselinestretch}{1.5} % 1.5 lines between lines
\parindent 0pt		  % sets leading space for paragraphs
% optional: cute, fancy headers
\usepackage{fancyhdr}
\pagestyle{fancy}
\fancyhead[LO]{Loughnan et al. 2023}
\fancyhead[RO]{Temporal Ecology Lab}
% more optionals! %

%\graphicspath{ {./DoseResponse_WriteupImages/} }% tell latex where to find photos 
\externaldocument[supp-]{Traitors_Manuscript_supp}

%%% end preambling. %%%

\begin{document}

%\renewcommand{\refname}{\CHead{}}%not sure what this was supposed to do 
\renewcommand{\bibname}{References}%names reference list 

\SweaveOpts{concordance=TRUE} % For RStudio hiccups

%Title ideas:
% old title: Phenological cue use varies with functional traits in North American woody plant communities
% Cues shaping woody plant temporal niche differs from cues driving species overall trait phenotype 
% ....need more

\title{Photoperiod shows strong relationships with leaf and wood traits but not woody plant budburst} %24Dec2023emw -- I really like the bold title! But it sounds so specific that it would likely limit where you could get the paper into review (... and it took me a lot of re-reading it to understand what you might mean. I am not sure we actually test this latter point, do we?). Maybe: Differences in leaf and wood traits predict phenological sensitivity to daylength more than temperature [Sounds weird, but something to work on -- maybe committee will have ideas.]
\date{\today}
\author{Deirdre Loughnan$^1$, Faith A M Jones$^1$, and E M Wolkovich$^1$}
\maketitle 

$^1$ Department of Forest and Conservation, Faculty of Forestry, University of British Columbia, 2424 Main Mall
Vancouver, BC Canada V6T 1Z4. \\


Corresponding Author: Deirdre Loughnan deirdre.loughnan@ubc.ca \\

<<label=runcode1,  echo=FALSE>>=
require(rstan)
setwd("~/Documents/github/Treetraits/rcode")
source("manuscriptValues.R")
setwd("~/Documents/github/Treetraits/docs")
@

\section*{Research questions}

\begin{enumerate}
\item Do phenological cue-trait relationships change across transects? Populations?
\item How do budburst cues relate to functional traits in temperate woody species?
\item How do shrub and tree species differ in their cue-trait relationships?
\end{enumerate}

\section*{Materials and Methods}
\subsection*{Field sampling}

\begin{enumerate}
\item General pop description
\begin{enumerate}
\item Combined \emph{in situ} trait data with budburst data from two growth chamber cutting experiments
\item Both datasets span latitudinal gradient of 4-6$^{\circ}$ %24Dec2023emw -- I moved this up. 
\item Traits were measured across four eastern populations --- Harvard Forest, Massachusetts, USA (42.55$^{\circ}$N, 72.20$^{\circ}$W) and St. Hippolyte, Quebec, Canada (45.98$^{\circ}$N, 74.01$^{\circ}$W) and four western population --- Smithers (54.78$^{\circ}$N, 127.17$^{\circ}$W) and E.C. Manning Park (49.06$^{\circ}$N, 120.78$^{\circ}$W)
\item Growth chamber study --- cuttings collected from the most southern and northern populations in each transect
\end{enumerate}

\item Describing spp
\begin{enumerate}
\item Across populations --- measured \Sexpr{nSpp} species --- \Sexpr{nSppE} eastern transect and \Sexpr{nSppW} western transect
\item Selected angiosperm spp that were most abundant in forest communities %24Dec2023emw -- add reasoning to focus on angiosperms -- both good for phylogenetic reasons and because leafout likely under more similar controls than if you added a bunch of evergreen conifers
\item Eastern transect: \Sexpr{nSppES} shrubs and \Sexpr{nSppET} trees
\item Western transect: \Sexpr{nSppWS} shrubs and \Sexpr{nSppWT} trees
\item Three species occurred in both transect
\end{enumerate}
\end{enumerate}

\subsection*{Functional traits}

\begin{enumerate}
\item General sampling info
\begin{enumerate}
\item Traits were measured in the summer prior to each growth chamber study.
\item Eastern transect: traits measured summer 2015---need to look up specific dates
\item Western transect: traits measured May 29 to July 30, 2019
\item For each --- measured traits for X-10 healthy, adult, individuals of each species
\end{enumerate}

\item Trait sampling --- structural/wood traits
\begin{enumerate}
\item Measured a total of five traits: height (n = \Sexpr{nHt}), DBH (n = \Sexpr{nDBH}), SSD (n = \Sexpr{nSSD}), LMA (n = \Sexpr{nLMA}), LNC (n = \Sexpr{nLNC})
\item Traits were measured according to recommendations of Perez-Harguindeguy2013.
\item Height was measured using a range finder (XX brand etc.).
\item Diameter at breast height was measured 1.42 m from the ground.
\item Wood volume was measured within 12 hours of collection --- 10 cm sample taken from tree branches or shrub primary stems --- measured using the water displacement method
\item Branch segments were dried at 105$^{\circ}$C for 24h and weighted.
\end{enumerate}

\item Trait sampling --- leaf traits
\begin{enumerate}
\item Leaf traits were measured for five haphazardly selected, fully expanded, and hardened leaves 
\item High resolution scans of leaf area taken using Canon flatbed scanner within 12 hours of collection
\item Leaf area was then quantified using the ImageJ software
\item Leaves were dried for 48h at 70$^{\circ}$C and weighed using a precision balance.
\end{enumerate}
\end{enumerate}

\subsection*{Growth chamber study} %24Dec2023emw -- I would refer to your other chapter for much of this, and try to publish that paper first so you can refer to it when submitting to a journal. This will cut down the methods a good bit. 
\begin{enumerate}
\item General information
\begin{enumerate}
\item To collect branch cuttings for growth chamber study --- returned to our highest and lowest latitude populations in each transect
\item Eastern transect: Hippolyte and Harvard Forested visited again in 20-28 January for growth chamber study --- study conducted at Arnold Arboretum
\item Western transect: traits measured May 29 to July 30, 2019 --- Smithers and Manning park visited again in 19-28 October, 2019 --- study conducted at UBC
\end{enumerate}

\item Treatments and duration
\begin{enumerate}
\item For both growth chamber studies --- 8 distinct treatments:
\item two levels of chilling --- no additional chilling or 30 days at 4$^{\circ}$C = eastern study, and 30 days or 70 days of chilling at 4$^{\circ}$C for our western study --- all dark
\item two levels of forcing—a cool regime of 15:5$^{\circ}$C and a warm regime of 20:10$^{\circ}$C
\item two photoperiods of either 8 or 12 hours
\item For detailed disucssion of study differences see Loughnan et al. (phenology paper)
\end{enumerate}

\item Data collection --- BBCH
\begin{enumerate}
\item Phenological stages were based on BBCH scale adapted for our specific species
\item Observations made every 1-3 days for each sample
\item stages were recorded up to full leaf expansion --- limited our analysis to budburst 
\item Eastern study lasted for 82 days, 19320 observations---add Sexpr obj
\item Western study lasted for 113 days, 47844 observations
\end{enumerate}

\end{enumerate}

\subsection*{Statistical Anlaysis}

\begin{enumerate}
\item Introduce approach and why it is useful:
\begin{enumerate}
\item Our analysis combined the trait data with the budburst data from the growth chamber study
\item Built joint model for each trait---directly models the relationship between leaf and structural traits and budburst 
\item Approach carries through uncertainty between trait and phenology data---combines observational trait data with experimental phenology data
\end{enumerate}

\item Begin to describe the model:
\begin{enumerate}
\item hierarchical linear model---partitioning variation of individual observations (\emph{i}) of a given trait value ($y_{\text{trait}[i]}$) to the effects of species (\emph{sp id}), and population-level differences arising from transects (\emph{transect id}) or the interaction between transects and latitude (\emph{transect} $\times$ \emph{latitude}), and residual variation or 'measurement error' ($\sigma_{\text{trait}}$)
\item Transect included as a dummy variable and latitude as a continuous variable  %24Dec2023emw -- say 'categorical' instead of dummy -- more people know what you mean then, and the goal is to be understandable to the most people.
\item Latitude values z-scored %24Dec2023emw -- weird choice -- why? I guess okay, but be prepared to explain why ONLY this was z-scored. I would probably combine this and the below in a sentence saying you worked mainly in natural units, but made several small changes for the model numerical stability. You could ask Mike his advice on how to explain/phrase when he visits. 
\item Most traits were modeled using their natural units---except LMA was rescaled by 100
\end{enumerate}

\item describe trait part of model
\begin{enumerate}
\item Model gives unique estimates for each species and species-level variance ($\alpha_{\text{sp[sp id]}}$)---partial pooling---controls for variation in the number of trait estimates per spp and trait variability 
\item Estimate for differences between transect ($\beta_{transect}$) and the interaction between transects and latitude ($\beta_{transect \times latitude}$) 
\item These species-level estimates of traits become predictors of species-level estimates of each cue--- ($\beta_{\text{force[sp]}}$, $\beta_{\text{chill[sp]}}$, $\beta_{\text{photo[sp]}}$) 
\end{enumerate}

Trait model: %24Dec2023emw -- math is wrong, if you have a grand mean then you don't have mu in the following normal equation lines, right? ... I am skipping the rest of the math until you cross-check this math against your stan code more. 
\begin{align}
\mu_{trait} & = \alpha_{\text{grand trait}} + \alpha_{\text{sp[sp id]}} + \beta_{\text{transect}} +\beta_{\text{transect} \times \text{latitude}} \\
\beta_{transect} &  \sim normal( \mu_{transect}, \sigma_{\text{transect}}) \nonumber \\
\beta_{\text{transect} \times \text{latitude}} &  \sim normal( \mu_{\text{transect} \times \text{latitude}}, \sigma_{\text{transect} \times \text{latitude}}) \nonumber 
\end{align}

trait-cue relationship:
\begin{align}
\beta_{\text{chill[sp]}} & = \alpha_{\text{chill}[sp]} + \beta_{\text{trait}.\text{chill}} \times \alpha_{\text{trait sp[sp]}} \nonumber \\
\beta_{\text{force[sp]}} & = \alpha_{\text{force}[sp]} + \beta_{\text{trait}.\text{force}} \times \alpha_{\text{trait sp[sp]}} \\
\beta_{\text{photo[sp]}} & = \alpha_{\text{photo}[sp]} + \beta_{\text{trait}.\text{photo}} \times \alpha_{\text{trait sp[sp]}} \nonumber 
\end{align}

\item Explain phenology part of model
\begin{enumerate}
 \item Across each spp---get esti of overall effect of each trait on cue ($\beta_{\text{trait}.\text{chill}}$, $\beta_{\text{trait}.\text{force}}$, $\beta_{\text{trait}.\text{photo}}$)
\item and estimate of species-level cue variation not explained by traits ($\alpha_{\text{chill}[sp]} $, $\alpha_{\text{force}[sp]}$, $\alpha_{\text{photo}[sp]}$) = how well trait effects explain species-level differences
\item From this we can estimate individual species responses to cues ($C_i$, $F_i$, $P_i$, respectively---z-scored)---with residual variation across species ($\alpha_{\text{pheno[sp]}}$) and observations ($\sigma_{\text{pheno}}$)
\item Partial pooling for residual variation across species and variation in cues not attributed to the trait
\end{enumerate}

\begin{align}
\mu_{pheno} & = \alpha_{\text{pheno[sp]}}+ \beta_{\text{chill[sp]}} \times C_i + \beta_{\text{force[sp]}}\times F_i + \beta_{\text{photo[sp]}} \times P_i\\
y_{\text{pheno[i]}} & \sim normal( \mu_{pheno}, \sigma_{\text{pheno}}) \nonumber 
\end{align}

\begin{align}
\alpha_{\text{pheno}} \sim normal(\mu_{\alpha_{\text{pheno}}},\sigma_{\alpha_{\text{pheno}}}) \\
\alpha_{\text{force}} \sim normal(\mu_{\alpha_{\text{force}}},\sigma_{\alpha_{\text{force}}}) \nonumber \\
\alpha_{\text{chill}} \sim normal(\mu_{\alpha_{\text{chill}}},\sigma_{\alpha_{\text{chill}}}) \nonumber \\
\alpha_{\text{photo}} \sim normal(\mu_{\alpha_{\text{photo}}},\sigma_{\alpha_{\text{photo}}}) \nonumber
\end{align}

\item General info about model checks etc.:
\begin{enumerate}
\item weakly informative priors
\item validated model priors using prior predictive checks
\item model was coded in the Stan programming language and fit using the rstan package cite rstan2018
\item Four chains (4000-6000 total sampling iterations), and all models met basic diagnostic checks, including no divergences, high effective sample size (\emph{$n_{eff}$}), and $\hat{R}$ close to 1---LMA model still has low ESS---issue with neff---otherwise this is true
\item 90\% UI given in text

\end{enumerate} 
\end{enumerate} 

\section*{Results}

\begin{enumerate} %24Dec2023emw  -- reads more like discussion, I would save almost all of this text for the discussion I think. You could instead open with some of the numbers you have in the methods (this will also slim the methods!) -- numbers for each trait, how many species, phenology etc. (or give ranges and refer to a table in supp). Opening results with how much data you have is usually good and you can weave in a few reminders of the methods -- including joint model, populations etc. (for example, In total we collected XX trait data etc... Using a joint modeling approach we then combined them with data from XX cuttings across XX species in a chamber experiment. 
\item Our study = one of the first to combine trait data with phenological cue responses for the same individuals and across species distributions.
\begin{enumerate}
\item Includes plant communities in eastern and western deciduous forests of North America
\item Samples collected from multiple populations---modelling approach that accounts for variation across populations and transects
\item Joint modelling approach = use sp-level estimates for traits to understand phenological cue responses and budburst timing
\item Taking a community-level approach---with woody tree and shrub species = different growth strategies and presumably suites of traits
\end{enumerate}

% 1. Do phenological cue-trait relationships change across transects? Populations?
\item Traits differed in their population-level variation
% Ht:  population effect (-ve) but latxtran effect crosses zero (95% UI)
% LMA:  strong latxtran interaction and pop effect both +ve
% DBH: population effect (-ve) but -ve latxtran effect  (95% UI crosses zero)
% SSD: no population and latxtran effect (95% UI crosses zero)
% LNC strong latxtran interaction

%dlDec20: the height result seems strange to me, that the model would estimate greater height for the west coast that has so many more shrubs, both have left skewed height distribution, but the west coast does have some very tall trees
\begin{enumerate}
\item Most of our traits varied across populations---either between the two transects (main effect of transect only) or by latitudes within each transect (an interactive effect between transect and latitude) %24Dec2023emw  -- rewrote end less statistically -- 
\item Height differed between our eastern and western transect (\Sexpr{htTran}, UI: \Sexpr{lower_htTran},\Sexpr{upper_htTran}), with a weak effect of latitude  %24Dec2023emw  -- where is taller? And what is this weak effect? Please give all the numbers for stats you're reporting ... and please adjust the rest below so you're consistent in phrasing and giving directionality and all stats. (This also makes it hard to address your question, but be sure you are taking into account all transect and latitude effects when you try to interpret this effect. )
\item DBH (\Sexpr{dbhLatTran}, UI: \Sexpr{lower_dbhLatTran},\Sexpr{upper_dbhLatTran}), and LMA (\Sexpr{lmaLatTran}, UI: \Sexpr{lower_lmaLatTran},\Sexpr{upper_lmaLatTran})---strong interactions between latitude and transect
\item Tree DBH and LMA both increased with latitude
\item LNC differed between the two transects (\Sexpr{lncTran}, UI: \Sexpr{lower_lncTran},\Sexpr{upper_lncTran})---greater in western transect
\item But no population-level variation in SSD
\item Fig. \ref{fig:tranInt} %24Dec2023emw -- I would end this section by contrasting population level variation versus species -- you want to remind readers that species differences DWARF population differences before you go ahead and focus on species below. 
\end{enumerate}
%2. What other functional traits relate to budburst phenology in temperate woody species?
% Multiple paragraphs --- discuss ht and DBH and SSD and then leaf traits %24Dec2023emw  -- I like the organized grouping of traits like this!
\item All traits related to at least one budburst cue---but responses were generally weak
\begin{enumerate}
\item Of our three cues---photoperiod strongest relationship with other traits
\item Our two structural traits = similar cue relationships---taller plants with greater DBH = stronger photoperiod responses = earlier bb under longer daylengths (\Sexpr{htMuPSpMean}, UI: \Sexpr{lower_htMuPSpMean}, \Sexpr{upper_htMuPSpMean} for height and (\Sexpr{dbhMuPSpMean}, UI: \Sexpr{lower_dbhMuPSpMean}, \Sexpr{upper_dbhMuPSpMean } for DBH) 
\item But no relationship between between ring porosity of wood with cues---see similar cue estimates across each of the four ring types \ref{fig:ringPorosity}.
\end{enumerate}

\item leaf traits varied more in their cue responses %24Dec2023emw -- varied how? Across cues or species or? 
%24Dec2023emw -- try to clean up and remove too many different versions of 'cues' now if possible. Remember you can use the cues themselves (chilling, forcing photoperiod) or just 'cues' or 'treatments' or such. Check figure legends for this too. 
\begin{enumerate}
\item LMA showed strong responses to photoperiod with low LMA species advancing in bb with longer photoperiods (\Sexpr{lmaMuPSpMean}, UI: \Sexpr{lower_lmaMuPSpMean}, \Sexpr{upper_lmaMuPSpMean})
\item But LNC had no responses to any of our three cues
\end{enumerate}

\item Regardless of trait effects---our joint modeling approach still estimated phenological cue responses in line with previous work. %24Dec2023emw  -- again, this reads as discussion as a topic sentence (understandable -- topic sentences are HARD for results), maybe you just need to say 'Regardless of trait effects, we found temperature effects on budburst far stronger than photoperiod.'
%24Dec2023emw -- also, you should adjust this to remind readers that these cues drive budburst, either at the start or end (end would flow better to next paragraph). 
\begin{enumerate}
\item All models showed earlier budburst in response to all three cues
\item Individual spp varied in both their timing and cue responses---but generally responses were strongest for chilling and weakest for photoperiod.
%24Dec2023emw -- I think you probably need a sentence reminding folks that the cues lead to budburst (see comments above) and that the budburst order can vary by trait in this model (and why) for them to get this next part below... 
\item Only our LMA model produced unique cue estimates---estimating photoperiod cues (\Sexpr{lmaMuPSpMean}, UI: \Sexpr{lower_lmaMuPSpMean}, \Sexpr{upper_lmaMuPSpMean}) that were slightly stronger than forcing cues (\Sexpr{lmaMuFSpMean}, UI: \Sexpr{lower_lmaMuFSpMean}, \Sexpr{upper_lmaMuFSpMean}) (Table \ref{tabLMA})
\item ref Fig. \ref{fig:muCuePlot} and Fig. \ref{fig:muCueTraitPlot}
\end{enumerate}

% How do shrub and tree species differ in their cue-trait relationships?
%24Dec2023emw -- I tried moving this up ... I was thinking it would work better since it links to shrubs, tree etc. but then I got an idea of your ordering and moved it back down. I think your ordering is good, but you need to adjust the text to make it work. I think you likely need to transition better from your last point above to guide the reader to understand the below; remember that it will be really unnatural to most.  
\item Including trait effects provides novel insights into how they relate to phenology and cues %24Dec2023emw -- This one line reads more discussion-y, so I think you need a new topic sentence for the points below (which seem good for the results). 
\begin{enumerate}
\item Estimates bb using our model parameters show clear differences in bb timing between tree and shrub spp for some traits but not all (Fig. \ref{fig:bbShrubTree})
\item Height showed strong correlations between bb timing and trait values---shrub spp were estimated to bb earlier---especially under stronger cues---tree spp were later
\item But this was not the case for leaf traits---LNC showed no distinct separation between species functional groups (Fig. \ref{fig:bbShrubTree})
%\item But species-level effects vary across traits = unique effects on cue responses---estimated order of spp bb order differs between the two models
\end{enumerate}


\end{enumerate}

%24Dec2023emw -- looking good! Please work up edits to the outline here for methods and results and -- if you still have time before I can look at this again -- work on the discussion outline. (And if you still have time you could write up the methods.)

\clearpage

\section*{Figures}

\begin{figure}[ht]\centering\hfill
 \centering
 \includegraphics[width=\textwidth]{..//figures/intrxnPlots1006.pdf}
\caption{We found geographic differences for four of our functional traits, with the direction of the relationship varying across traits. Of our traits a. height, b. diameter at base height, c. leaf mass area, and e. leaf nitrogen content showed strong interactions between latitude and transect, while d. stem specific density showed no effects of geography. Dashed lines represent the western transect and solid lines the eastern transect.}
\label{fig:tranInt}
\end{figure}


% \begin{figure}[ht]\centering\hfill
%  \centering
%  \includegraphics[width=\textwidth]{..//figures/betaTraitxCueZ25.pdf}
% \caption{Only some traits were related to budburst phenological cues. For leaf mass area, stem specific density, and the ratio of carbon to nitrogen, traits no effect on budburst timing.}
% \label{fig:betaTraitxCue}
% \end{figure}

\begin{figure}[ht]\centering\hfill
 \centering
 \includegraphics[width=\textwidth]{..//figures/cuetrait1006.pdf}
\caption{Relationship between species traits and cue responses, for height (a-c), leaf mass area (d-f), diameter at breast height (g-i), stem specific density (j-l), and the leaf nitrogen content (m-o). Point colours representing different species groups, with tree species are depicted in maroon and shrub species in teal.}
\label{fig:traitSlopes}
\end{figure}

\begin{figure}[ht]\centering\hfill
 \centering
 \includegraphics[width=\textwidth]{..//figures/ringPorosityHeight1006.pdf}
\caption{Despite species wood structures causing differing growth strategies, we did not find this trait to correlate with differences in cue responses across species. Thinner lines represent the 90\% UI and thicker lines the 50\% UI. Here we show the results for height only.}
\label{fig:ringPorosity}
\end{figure}
\newpage

\begin{figure}[ht]\centering\hfill
 \centering
 \includegraphics[width=\textwidth]{..//figures/muCuePlots1006.pdf}
\caption{We found fairly consistent estimates for budburst cue responses to chilling, forcing, and photoperiod for each of our trait models: a. height, b. diameter at breast height, c. stem specific density, d. leaf mass area, and e. leaf nitrogen contnet. Lines represent 90\% uncertainty intervals.}
\label{fig:muCuePlot}
\end{figure}

\begin{figure}[ht]\centering\hfill
 \centering
 \includegraphics[width=\textwidth]{..//figures/muCueTraitPlots1006.pdf}
\caption{The relationships between traits and cue responses varied considerably across each of our trait models, a. height, b. diameter at breast height, c. stem specific density, d. leaf mass area, and e. leaf nitrogen content, and for individual cues. Lines represent 90\% uncertainty intervals. Note the differences in the scale of the x-axis.}
\label{fig:muCueTraitPlot}
\end{figure}

\begin{figure}[ht]\centering\hfill
 \centering
 \includegraphics[width=\textwidth]{..//figures/dotShrubTreeHtCN6.pdf}
\caption{We found budburst estimates differed between our full model (intercept plus cues, depicted as triangles for high cues and as circles for low cues), versus the intercepts only model (without cues, shown as squares). Species are ordered in increasing budburst dates for both the eastern (a and c) and western (b and d) populations, spanning from early budbursting shrubs, in red, to late budbursting trees in blue. For traits such as height (a and b) we found distinct partitioning of budburst across shrub and tree species, but this was not the case for all traits, with our model of leaf nitrogen content showing highly mixed budburst order of shrub and tree species (c and d). }
\label{fig:bbShrubTree}
\end{figure}
\newpage
\clearpage


\section*{Tables}
<<label= tableht, echo=FALSE , results= tex >>=

require(xtable)
require(rstan)

load("..//output/htContLat6.Rdata")

sum <- summary(mdlHt)$summary

fit <- rstan::extract(mdlHt)

mu_params_4 <- c(
  "b_tranE","b_tranlat",
  "muForceSp", "muChillSp", "muPhotoSp", 
  "betaTraitxForce","betaTraitxChill","betaTraitxPhoto")
  
meanz4 <- round(data.frame(sum[mu_params_4, "mean"]),1)
names(meanz4) <- "mean"

rownames(meanz4) = c( "Transect", "Transect x latitude",
                      "Forcing","Chilling", "Photoperiod",
                      "Trait x forcing","Trait x chilling", "Trait x photoperiod"
)

# now get the 90% UI:
bTranU <- round(quantile(fit$b_tranE, c(0.05, 0.25, 0.75,0.95)),1)
bTranLatU <- round(quantile(fit$b_tranlat, c(0.05, 0.25, 0.75,0.95)),1)
chillCueU <- round(quantile(fit$muChillSp, c(0.05, 0.25, 0.75,0.95)),1)
photoCueU <- round(quantile(fit$muPhotoSp, c(0.05, 0.25, 0.75,0.95)),1)
forceCueU <- round(quantile(fit$muForceSp, c(0.05, 0.25, 0.75,0.95)),1)
intrxnFU <- round(quantile(fit$betaTraitxForce, c(0.05, 0.25, 0.75,0.95)),1)
intrxnPU <- round(quantile(fit$betaTraitxPhoto, c(0.05, 0.25, 0.75,0.95)),1)
intrxnCU <- round(quantile(fit$betaTraitxChill, c(0.05, 0.25, 0.75,0.95)),1)
upper <- rbind(bTranU, bTranLatU,forceCueU, chillCueU, photoCueU,intrxnFU,intrxnCU,intrxnPU)

meanz4 <- cbind(meanz4,  upper)

print(xtable(meanz4, caption="Summary output from a joint Bayesian model of height and budburst phenology in which species are partially pooled. The effect of transect is modeled as a dummy variable and latitude as continuous in interaction term with transect. The model includes photoperiod and forcing as continuous variables, with all three cues z-scored to allow comparisons across cues.",label = "tabHt"),include.rownames=TRUE, caption.placement="top", hline.after=c(-1,0))


@


<<label= tableDBH, echo=FALSE , results= tex >>=

require(xtable)
require(rstan)

load("..//output/DBHContLat6.Rdata")

sum <- summary(mdlDBH)$summary

fit <- rstan::extract(mdlDBH)

mu_params_4 <- c(
  "b_tranE","b_tranlat",
  "muForceSp", "muChillSp", "muPhotoSp", 
  "betaTraitxForce","betaTraitxChill","betaTraitxPhoto")
  
meanz4 <- round(data.frame(sum[mu_params_4, "mean"]),1)
names(meanz4) <- "mean"

rownames(meanz4) = c( "Transect", "Transect x latitude",
                      "Forcing","Chilling", "Photoperiod",
                      "Trait x forcing","Trait x chilling", "Trait x photoperiod"
)

# now get the 90% UI:
bTranU <- round(quantile(fit$b_tranE, c(0.05, 0.25, 0.75,0.95)),1)
bTranLatU <- round(quantile(fit$b_tranlat, c(0.05, 0.25, 0.75,0.95)),1)
chillCueU <- round(quantile(fit$muChillSp, c(0.05, 0.25, 0.75,0.95)),1)
photoCueU <- round(quantile(fit$muPhotoSp, c(0.05, 0.25, 0.75,0.95)),1)
forceCueU <- round(quantile(fit$muForceSp, c(0.05, 0.25, 0.75,0.95)),1)
intrxnFU <- round(quantile(fit$betaTraitxForce, c(0.05, 0.25, 0.75,0.95)),1)
intrxnPU <- round(quantile(fit$betaTraitxPhoto, c(0.05, 0.25, 0.75,0.95)),1)
intrxnCU <- round(quantile(fit$betaTraitxChill, c(0.05, 0.25, 0.75,0.95)),1)

upper <- rbind(bTranU, bTranLatU,forceCueU, chillCueU, photoCueU,intrxnFU,intrxnCU,intrxnPU)

meanz4 <- cbind(meanz4, upper)

print(xtable(meanz4, caption="Summary output from a joint Bayesian model of DBH and budburst phenology in which species are partially pooled. The effect of transect is modeled as a dummy variable and latitude as continuous in interaction term with transect. The model includes photoperiod and forcing as continuous variables, with all three cues z-scored to allow comparisons across cues.",label = "tabDBH"),include.rownames=TRUE, caption.placement="top", hline.after=c(-1,0))
@


<<label= tableDBH, echo=FALSE , results= tex >>=

require(xtable)
require(rstan)

load("..//output/ssdContLat6.Rdata")

sum <- summary(mdlSSD)$summary

fit <- rstan::extract(mdlSSD)

mu_params_4 <- c(
  "b_tranE","b_tranlat",
  "muForceSp", "muChillSp", "muPhotoSp", 
  "betaTraitxForce","betaTraitxChill","betaTraitxPhoto")
  
meanz4 <- round(data.frame(sum[mu_params_4, "mean"]),1)
names(meanz4) <- "mean"

rownames(meanz4) = c( "Transect", "Transect x latitude",
                      "Forcing","Chilling", "Photoperiod",
                      "Trait x forcing","Trait x chilling", "Trait x photoperiod"
)

# now get the 90% UI:
bTranU <- round(quantile(fit$b_tranE, c(0.05, 0.25, 0.75,0.95)),1)
bTranLatU <- round(quantile(fit$b_tranlat, c(0.05, 0.25, 0.75,0.95)),1)
chillCueU <- round(quantile(fit$muChillSp, c(0.05, 0.25, 0.75,0.95)),1)
photoCueU <- round(quantile(fit$muPhotoSp, c(0.05, 0.25, 0.75,0.95)),1)
forceCueU <- round(quantile(fit$muForceSp, c(0.05, 0.25, 0.75,0.95)),1)
intrxnFU <- round(quantile(fit$betaTraitxForce, c(0.05, 0.25, 0.75,0.95)),1)
intrxnPU <- round(quantile(fit$betaTraitxPhoto, c(0.05, 0.25, 0.75,0.95)),1)
intrxnCU <- round(quantile(fit$betaTraitxChill, c(0.05, 0.25, 0.75,0.95)),1)

upper <- rbind(bTranU, bTranLatU,forceCueU, chillCueU, photoCueU,intrxnFU,intrxnCU,intrxnPU)

meanz4 <- cbind(meanz4, upper)

print(xtable(meanz4, caption="Summary output from a joint Bayesian model of SSD and budburst phenology in which species are partially pooled. The effect of transect is modeled as a dummy variable and latitude as continuous in interaction term with transect. The model includes photoperiod and forcing as continuous variables, with all three cues z-scored to allow comparisons across cues.",label = "tabSSD"),include.rownames=TRUE, caption.placement="top", hline.after=c(-1,0))
@

<<label= tableLMA, echo=FALSE , results= tex >>=

require(xtable)
require(rstan)

load("..//output/lmaContLat.Rdata")

sum <- summary(mdlLMA)$summary

fit <- rstan::extract(mdlLMA)

mu_params_4 <- c(
  "b_tranE","b_tranlat",
  "muForceSp", "muChillSp", "muPhotoSp", 
  "betaTraitxForce","betaTraitxChill","betaTraitxPhoto")
  
meanz4 <- round(data.frame(sum[mu_params_4, "mean"]),1)
names(meanz4) <- "mean"

rownames(meanz4) = c( "Transect", "Transect x latitude",
                      "Forcing","Chilling", "Photoperiod",
                      "Trait x forcing","Trait x chilling", "Trait x photoperiod"
)

# now get the 90% UI:
bTranU <- round(quantile(fit$b_tranE, c(0.05, 0.25, 0.75,0.95)),1)
bTranLatU <- round(quantile(fit$b_tranlat, c(0.05, 0.25, 0.75,0.95)),1)
chillCueU <- round(quantile(fit$muChillSp, c(0.05, 0.25, 0.75,0.95)),1)
photoCueU <- round(quantile(fit$muPhotoSp, c(0.05, 0.25, 0.75,0.95)),1)
forceCueU <- round(quantile(fit$muForceSp, c(0.05, 0.25, 0.75,0.95)),1)
intrxnFU <- round(quantile(fit$betaTraitxForce, c(0.05, 0.25, 0.75,0.95)),1)
intrxnPU <- round(quantile(fit$betaTraitxPhoto, c(0.05, 0.25, 0.75,0.95)),1)
intrxnCU <- round(quantile(fit$betaTraitxChill, c(0.05, 0.25, 0.75,0.95)),1)

upper <- rbind(bTranU, bTranLatU,forceCueU, chillCueU, photoCueU,intrxnFU,intrxnCU,intrxnPU)

meanz4 <- cbind(meanz4, upper)

print(xtable(meanz4, caption="Summary output from a joint Bayesian model of LMA and budburst phenology in which species are partially pooled. The effect of transect is modeled as a dummy variable and latitude as continuous in interaction term with transect. The model includes photoperiod and forcing as continuous variables, with all three cues z-scored to allow comparisons across cues.",label = "tabLMA"),include.rownames=TRUE, caption.placement="top", hline.after=c(-1,0))
@

<<label= tableCN, echo=FALSE , results= tex >>=

require(xtable)
require(rstan)

load("..//output/lncContLat.Rdata")

sum <- summary(mdlPerN)$summary

fit <- rstan::extract(mdlPerN)

mu_params_4 <- c(
  "b_tranE","b_tranlat",
  "muForceSp", "muChillSp", "muPhotoSp", 
  "betaTraitxForce","betaTraitxChill","betaTraitxPhoto")
  
meanz4 <- round(data.frame(sum[mu_params_4, "mean"]),1)
names(meanz4) <- "mean"

rownames(meanz4) = c( "Transect", "Transect x latitude",
                      "Forcing","Chilling", "Photoperiod",
                      "Trait x forcing","Trait x chilling", "Trait x photoperiod"
)

# now get the 90% UI:
bTranU <- round(quantile(fit$b_tranE, c(0.05, 0.25, 0.75,0.95)),1)
bTranLatU <- round(quantile(fit$b_tranlat, c(0.05, 0.25, 0.75,0.95)),1)
chillCueU <- round(quantile(fit$muChillSp, c(0.05, 0.25, 0.75,0.95)),1)
photoCueU <- round(quantile(fit$muPhotoSp, c(0.05, 0.25, 0.75,0.95)),1)
forceCueU <- round(quantile(fit$muForceSp, c(0.05, 0.25, 0.75,0.95)),1)
intrxnFU <- round(quantile(fit$betaTraitxForce, c(0.05, 0.25, 0.75,0.95)),1)
intrxnPU <- round(quantile(fit$betaTraitxPhoto, c(0.05, 0.25, 0.75,0.95)),1)
intrxnCU <- round(quantile(fit$betaTraitxChill, c(0.05, 0.25, 0.75,0.95)),1)

upper <- rbind(bTranU, bTranLatU,forceCueU, chillCueU, photoCueU,intrxnFU,intrxnCU,intrxnPU)

meanz4 <- cbind(meanz4, upper)

print(xtable(meanz4, caption="Summary output from a joint Bayesian model of LNC and budburst phenology in which species are partially pooled. The effect of transect is modeled as a dummy variable and latitude as continuous in interaction term with transect. The model includes photoperiod and forcing as continuous variables, with all three cues z-scored to allow comparisons across cues.",label = "tabLNC"),include.rownames=TRUE, caption.placement="top", hline.after=c(-1,0))
@

\end{document}